### ISSUE TITLE
run histedit

### ISSUE THREAD

**Issue by ouboub** [jojojames/hg-histedit#2]
Hi

i run commit and histedit from the command line, like this
```
!TMP=$($HG root) $HG histedit "$@"
```
or to be precise I use an alias 
```
histed = !TMP=$($HG root) $HG histedit "$@"
```
the advantage of this approach is that it calls emacs, in the directory of the repository and not in /tmp
could hg-histedit do the same?

regards
Uwe Brauer

**Comment by jojojames** [comment]
Is there a tangible benefit to doing this? I wouldn't be opposed to supporting this if there were.

**Comment by ouboub** [comment]
Sorry, I did not see your answers, benefit would be that one can use `log-edit-insert-changelog` 
which is rather difficult if histedit operates in /tmp

I have a solution based on a shell script but struggle with a lisp solution.
If you wish I can fork your repository and make a `merge/pull-request`
